# -*- coding: utf-8 -*-
"""
02_process_rossler_figS1_figS2_original_xy.py

Process Rossler raw data and generate Fig. S1 and Fig. S2 using the same core
calculation as the uploaded original Rossler script.

Input
-----
rossler_raw_data.npz
    Generated by 01_generate_rossler_raw_data.py.

Output
------
rossler_figS_original_xy_svg/
    figS1.svg
    figS2.svg

Core calculation matched to the uploaded original script
-------------------------------------------------------
1. Use only observed x and y:
       observed_coordinate_matrix  = [X, Y]
       observed_velocity_matrix = [dX, dY]

2. Use:
       embedding_dimension = 4000 - (5 - 1) * 1
       delay = 1

3. Build Hankel matrices for x, y and dx/dt, dy/dt.

4. Select the retained SVD rank by cumulative sum of singular values:
       cumulative_sum >= 0.99 * total_sum

5. Reconstruct the Hankel matrix:
       reconstructed_observable_matrix_V = U_r @ diag(s_r) @ Vh_r

6. Use:
       observable_velocity_matrix_V_dot = observable_velocity_matrix_H_dot
       step = 316

7. Compute closure_defect_beta_values using the same sliding-window closure-defect loop.

8. Plot Fig. S2 as beta and hidden z reference.

Only SVG files are saved.
"""

import os
import shutil
import warnings

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from matplotlib.ticker import MaxNLocator

warnings.filterwarnings("ignore")


# ============================================================
# Files
# ============================================================

RAW_DATA_FILE = "rossler_raw_data.npz"
OUTPUT_DIR = "rossler_figS"


# ============================================================
# Parameters matched to the uploaded original script
# ============================================================

ANALYSIS_START_INDEX = 2000
ANALYSIS_END_INDEX = 6000

DELAY_TAU = 1
OBSERVABLE_WINDOW_LENGTH = 4000 - (5 - 1) * DELAY_TAU

SVD_ENERGY_RATIO_BY_SINGULAR_VALUE_SUM = 0.99

WINDOW_T = 316

LOCAL_MAXIMUM_SEARCH_WINDOW = 50
LOCAL_MAXIMUM_BETA_THRESHOLD = 9.0

PEAK_VALLEY_PROMINENCE_FACTOR = 0.315
PEAK_VALLEY_DISTANCE = 20

# The uploaded original plotting line used t[0:...], but the manuscript figure
# uses the absolute segment time around 20-60. Keep absolute time by default.
USE_ABSOLUTE_SEGMENT_TIME = True


# ============================================================
# Figure style
# ============================================================

plt.rcParams["font.family"] = "Arial"
plt.rcParams["mathtext.fontset"] = "custom"
plt.rcParams["mathtext.rm"] = "Arial"
plt.rcParams["mathtext.it"] = "Arial:italic"
plt.rcParams["mathtext.bf"] = "Arial:bold"
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["svg.fonttype"] = "none"


# ============================================================
# Basic helpers
# ============================================================

def load_raw_data():
    """Load raw Rossler data."""
    if not os.path.exists(RAW_DATA_FILE):
        raise FileNotFoundError(
            f"{RAW_DATA_FILE} was not found. Run 01_generate_rossler_raw_data.py first."
        )
    return np.load(RAW_DATA_FILE)




def read_raw_array(raw_data, original_key, renamed_key):
    """Read original key first, then renamed key for compatibility."""
    if original_key in raw_data:
        return raw_data[original_key]
    if renamed_key in raw_data:
        return raw_data[renamed_key]
    raise KeyError(
        f"Neither '{original_key}' nor '{renamed_key}' is in the archive. "
        f"Available keys: {list(raw_data.keys())}"
    )


def reset_output_dir():
    """Create a clean SVG-only output directory."""
    if os.path.isdir(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR)
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def save_svg(fig, file_stem):
    """Save one figure as SVG only."""
    path = os.path.join(OUTPUT_DIR, f"{file_stem}.svg")
    fig.savefig(path, format="svg", facecolor="white", transparent=False)
    print(f"Saved: {path}")


def paper_axes(ax):
    """Apply a simple manuscript-style axis format."""
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.0)
    ax.spines["bottom"].set_linewidth(1.0)
    ax.tick_params(direction="out", length=3.5, width=1.0, pad=3)


# ============================================================
# Hankel construction
# ============================================================

def build_observable_matrix_H_like_original(observed_data_matrix):
    """
    Build Hankel matrices exactly following the uploaded original script.

    For each observed row:
        num_rows = len(row_data) - delay * (embedding_dimension - 1)
        num_cols = delay * embedding_dimension

    Then stack all row-wise Hankel matrices vertically.
    """
    n_observed_rows = observed_data_matrix.shape[0]
    observable_matrix_blocks_H = []

    for i in range(n_observed_rows):
        row_data = observed_data_matrix[i, :]

        num_rows = len(row_data) - DELAY_TAU * (OBSERVABLE_WINDOW_LENGTH - 1)
        num_cols = DELAY_TAU * OBSERVABLE_WINDOW_LENGTH

        if num_rows <= 0:
            raise ValueError(
                f"Invalid Hankel shape: num_rows={num_rows}. "
                f"Check OBSERVABLE_WINDOW_LENGTH={OBSERVABLE_WINDOW_LENGTH}."
            )

        observable_matrix_block_H = np.zeros((num_rows, num_cols))

        for k in range(num_rows):
            for ell in range(OBSERVABLE_WINDOW_LENGTH):
                observable_matrix_block_H[k, ell * DELAY_TAU:(ell + 1) * DELAY_TAU] = row_data[k + ell * DELAY_TAU]

        observable_matrix_blocks_H.append(observable_matrix_block_H)

    return np.vstack(observable_matrix_blocks_H)


# ============================================================
# SVD and beta calculation
# ============================================================

def reconstruct_observable_matrix_H_by_original_svd(observable_matrix_H):
    """
    Reconstruct the Hankel matrix after retaining singular values according to
    the cumulative singular-value sum criterion used in the original script.
    """
    left_singular_vectors_U, singular_values, right_singular_vectors_Vh = np.linalg.svd(observable_matrix_H, full_matrices=False)

    total_sum = np.sum(singular_values)
    cumulative_sum = np.cumsum(singular_values)

    retained_rank_r = (
        np.argmax(cumulative_sum >= SVD_ENERGY_RATIO_BY_SINGULAR_VALUE_SUM * total_sum)
        + 1
    )

    print("retained_rank_r =", retained_rank_r)

    singular_values_r = singular_values[:retained_rank_r]
    left_singular_vectors_U_r = left_singular_vectors_U[:, :retained_rank_r]
    right_singular_vectors_Vh_r = right_singular_vectors_Vh[:retained_rank_r, :]

    reconstructed_observable_matrix_V = left_singular_vectors_U_r @ np.diag(singular_values_r) @ right_singular_vectors_Vh_r

    return reconstructed_observable_matrix_V, retained_rank_r


def compute_closure_defect_beta_like_original(reconstructed_observable_matrix_V, observable_velocity_matrix_V_dot):
    """
    Compute closure_defect_beta_values and A_t_column_norm_values using the same loop as the
    uploaded original script.
    """
    closure_defect_beta_values = []
    A_t_column_norm_values = []

    for i in range(0, OBSERVABLE_WINDOW_LENGTH - WINDOW_T, 1):
        start = i
        end = start + WINDOW_T

        V_dot_t = observable_velocity_matrix_V_dot[:, start:end]
        V_t = reconstructed_observable_matrix_V[:, start:end]

        A_t = V_dot_t @ np.linalg.pinv(V_t)

        A_t_column_norms = np.linalg.norm(A_t, axis=0)
        A_t_column_norm_mean = np.mean(A_t_column_norms)

        R_t = V_dot_t - A_t @ V_t
        R_t_row_norms = np.linalg.norm(R_t, axis=1)
        beta_t = np.mean(R_t_row_norms)

        A_t_column_norm_values.append(A_t_column_norm_mean)
        closure_defect_beta_values.append(beta_t)

    closure_defect_beta_values = np.asarray(closure_defect_beta_values, dtype=float)
    A_t_column_norm_values = np.asarray(A_t_column_norm_values, dtype=float)

    beta_mean_value = np.mean(closure_defect_beta_values)
    beta_variance_value = np.var(closure_defect_beta_values)
    variance_over_mean = beta_variance_value / beta_mean_value

    print("variance_over_mean =", variance_over_mean)

    return closure_defect_beta_values, A_t_column_norm_values


def find_local_maxima_like_original(closure_defect_beta_values, time_vector):
    """
    Find local maxima using the same window and threshold logic as the uploaded
    original script.
    """
    local_beta_maxima_values = []
    local_beta_maxima_indices = []
    local_beta_maxima_times = []

    window_size = LOCAL_MAXIMUM_SEARCH_WINDOW

    for i in range(window_size, len(closure_defect_beta_values) - window_size):
        window = closure_defect_beta_values[i - window_size:i + window_size + 1]
        max_index_in_window = np.argmax(window)

        if max_index_in_window == window_size:
            local_beta_maximum_value = window[window_size]

            if local_beta_maximum_value > LOCAL_MAXIMUM_BETA_THRESHOLD:
                local_beta_maxima_values.append(local_beta_maximum_value)
                local_beta_maxima_indices.append(i)
                local_beta_maxima_times.append(time_vector[i])

    local_beta_maxima_values = np.asarray(local_beta_maxima_values, dtype=float)
    local_beta_maxima_indices = np.asarray(local_beta_maxima_indices, dtype=int)
    local_beta_maxima_times = np.asarray(local_beta_maxima_times, dtype=float)

    for value, time_value in zip(local_beta_maxima_values, local_beta_maxima_times):
        print(f"local maximum: {value}, time: {time_value}")

    return local_beta_maxima_values, local_beta_maxima_indices, local_beta_maxima_times


# ============================================================
# Fig. S1
# ============================================================

def detect_all_peaks_and_valleys(signal):
    """
    Detect maxima and minima from the observed x signal for Fig. S1.
    """
    prominence = PEAK_VALLEY_PROMINENCE_FACTOR * (np.max(signal) - np.min(signal))

    peaks_up, _ = find_peaks(
        signal,
        prominence=prominence,
        distance=PEAK_VALLEY_DISTANCE
    )

    peaks_down, _ = find_peaks(
        -signal,
        prominence=prominence,
        distance=PEAK_VALLEY_DISTANCE
    )

    all_peak_valley_extrema = np.sort(np.concatenate([peaks_up, peaks_down]))

    print(
        f"Detected maxima: {len(peaks_up)}, "
        f"minima: {len(peaks_down)}, "
        f"total extrema: {len(all_peak_valley_extrema)}"
    )

    return all_peak_valley_extrema


def interval_count_distribution(peak_valley_extrema_indices):
    """Return interval values and their interval_counts."""
    if len(peak_valley_extrema_indices) < 2:
        return np.array([], dtype=int), np.array([], dtype=int), np.array([], dtype=int)

    peak_valley_intervals = np.diff(peak_valley_extrema_indices).astype(int)
    interval_values, interval_counts = np.unique(peak_valley_intervals, return_counts=True)

    return peak_valley_intervals, interval_values, interval_counts


def plot_figS1_window_distribution(all_peak_valley_extrema):
    """Plot Fig. S1: peak-valley interval distribution."""
    peak_valley_intervals, interval_values, interval_counts = interval_count_distribution(all_peak_valley_extrema)
    selected_window_T = int(peak_valley_intervals.max()) if peak_valley_intervals.size > 0 else WINDOW_T

    fig = plt.figure(figsize=(6.2, 2.2), dpi=300, facecolor="white")
    ax = fig.add_axes([0.16, 0.32, 0.78, 0.58], facecolor="white")

    if interval_values.size > 0:
        ax.bar(
            interval_values,
            interval_counts,
            width=0.9,
            edgecolor="black",
            linewidth=0.6,
            alpha=0.90,
            color="black"
        )

        ax.axvline(
            WINDOW_T,
            linestyle="--",
            linewidth=1.1,
            color="black"
        )

        ymax = max(int(interval_counts.max()), 1)
        ax.set_ylim(0, ymax * 1.20)

        ax.set_xlabel(r"Peak-valley interval $\Delta k$ (samples)", fontsize=16)
        ax.set_ylabel("Count", fontsize=16)
        ax.tick_params(axis="both", labelsize=14)
        ax.xaxis.set_major_locator(MaxNLocator(nbins=5))
        ax.yaxis.set_major_locator(MaxNLocator(nbins=3))

    else:
        ax.text(
            0.5,
            0.5,
            "Not enough extrema",
            ha="center",
            va="center",
            fontsize=16,
            transform=ax.transAxes
        )
        ax.set_axis_off()

    paper_axes(ax)
    save_svg(fig, "figS1")
    plt.close(fig)

    print("Fig. S1 maximum peak-valley interval =", selected_window_T)
    print("Fig. S2 calculation step =", WINDOW_T)


# ============================================================
# Fig. S2
# ============================================================

def plot_figS2_closure_defect_beta_and_hidden_z(closure_defect_beta_values, hidden_z_reference, closure_defect_beta_time, hidden_z_time):
    """
    Plot Fig. S2 using the same beta sequence as the uploaded original script.

    The hidden z coordinate is shown as a reference curve only.
    """
    fig = plt.figure(figsize=(6.2, 2.2), dpi=300, facecolor="white")
    ax = fig.add_axes([0.13, 0.28, 0.73, 0.64], facecolor="white")
    ax_right = ax.twinx()

    line_beta, = ax.plot(
        closure_defect_beta_time,
        closure_defect_beta_values,
        linestyle="-",
        label=rf"$\beta$ $(T={WINDOW_T})$",
        color="#C42238",
        alpha=0.85,
        linewidth=1.2
    )

    line_z, = ax_right.plot(
        hidden_z_time,
        hidden_z_reference,
        linestyle="-",
        label=r"$z$",
        color="#262626",
        alpha=0.55,
        linewidth=1.2
    )

    ax.set_ylabel(r"$\beta$", fontsize=16, color="black")
    ax_right.set_ylabel(r"$z$", fontsize=16, color="black")
    ax.set_xlabel(r"$t$", fontsize=16, color="black")

    ax.tick_params(axis="both", labelcolor="black", labelsize=14)
    ax_right.tick_params(axis="both", labelcolor="black", labelsize=14)

    ax.xaxis.set_major_locator(MaxNLocator(nbins=5))
    ax.yaxis.set_major_locator(MaxNLocator(nbins=4))
    ax_right.yaxis.set_major_locator(MaxNLocator(nbins=4))

    ax.set_xlim(hidden_z_time[0], hidden_z_time[-1])

    ax.spines["top"].set_visible(False)
    ax_right.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax_right.spines["left"].set_visible(False)

    ax.legend(
        [line_beta, line_z],
        [rf"$\beta$ $(T={WINDOW_T})$", r"$z$"],
        fontsize=11,
        loc="upper right",
        frameon=False,
        ncol=2
    )

    save_svg(fig, "figS2")
    plt.close(fig)


# ============================================================
# Main workflow
# ============================================================

def main():
    """Run Rossler processing and generate Fig. S1 and Fig. S2."""
    reset_output_dir()

    raw = load_raw_data()

    t = raw["t"]
    x = raw["x"]
    y = raw["y"]
    z = raw["z"]
    dx_dt = read_raw_array(raw, "dx_dt", "x_dot")
    dy_dt = read_raw_array(raw, "dy_dt", "y_dot")

    X = x[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]
    Y = y[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]
    Z = z[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]

    dX = dx_dt[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]
    dY = dy_dt[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]

    # This is the key point: only X and Y are used in the calculation.
    observed_coordinate_matrix = np.vstack((X, Y))
    observed_velocity_matrix = np.vstack((dX, dY))

    print("Using observed coordinates only: X and Y.")
    print("mar.shape =", observed_coordinate_matrix.shape)
    print("dmar.shape =", observed_velocity_matrix.shape)
    print("embedding_dimension =", OBSERVABLE_WINDOW_LENGTH)
    print("step =", WINDOW_T)

    observable_matrix_H = build_observable_matrix_H_like_original(observed_coordinate_matrix)
    observable_velocity_matrix_H_dot = build_observable_matrix_H_like_original(observed_velocity_matrix)

    print("hankel_mar.shape =", observable_matrix_H.shape)
    print("hankel_dmar.shape =", observable_velocity_matrix_H_dot.shape)

    reconstructed_observable_matrix_V, retained_rank_r = reconstruct_observable_matrix_H_by_original_svd(observable_matrix_H)
    observable_velocity_matrix_V_dot = observable_velocity_matrix_H_dot

    closure_defect_beta_values, A_t_column_norm_values = compute_closure_defect_beta_like_original(reconstructed_observable_matrix_V, observable_velocity_matrix_V_dot)
    _ = A_t_column_norm_values

    if USE_ABSOLUTE_SEGMENT_TIME:
        closure_defect_beta_time = t[ANALYSIS_START_INDEX:ANALYSIS_START_INDEX + len(closure_defect_beta_values)]
        hidden_z_time = t[ANALYSIS_START_INDEX:ANALYSIS_START_INDEX + OBSERVABLE_WINDOW_LENGTH]
    else:
        closure_defect_beta_time = t[:len(closure_defect_beta_values)]
        hidden_z_time = t[:OBSERVABLE_WINDOW_LENGTH]

    hidden_z_reference_for_plot = Z[:OBSERVABLE_WINDOW_LENGTH]

    find_local_maxima_like_original(closure_defect_beta_values, closure_defect_beta_time)

    all_peak_valley_extrema = detect_all_peaks_and_valleys(observable_matrix_H[0, :])

    plot_figS1_window_distribution(all_peak_valley_extrema)
    plot_figS2_closure_defect_beta_and_hidden_z(closure_defect_beta_values, hidden_z_reference_for_plot, closure_defect_beta_time, hidden_z_time)

    print("Finished. SVG figures are saved in:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
