# -*- coding: utf-8 -*-
"""
02_process_ks_figures_article_params.py

Read ks_raw_data.npz generated by 01_generate_ks_raw_data.py and reproduce
only the KS Fig. 3(b), Fig. 3(c), and Fig. 3(d) panels.

This version uses manuscript-consistent parameter names and values:

    FOURIER_MODES = 16
    NU = 0.028509
    DELTA_T = 0.01
    WINDOW_T1 = 83
    WINDOW_T2 = 437
    RETAINED_RANK_R1 = 9
    RETAINED_RANK_R2 = 12

Important:
    The x-axis uses the absolute raw simulation time t.
    No local-time shift is applied.

Only SVG files are saved.
"""

import os
import shutil
import warnings

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from matplotlib.ticker import MaxNLocator

warnings.filterwarnings("ignore")


# ============================================================
# Files
# ============================================================

RAW_DATA_FILE = "ks_raw_data.npz"
OUTPUT_DIR = "ks_results"


# ============================================================
# Manuscript parameters
# ============================================================

FOURIER_MODES = 16
NU = 0.028509
DELTA_T = 0.01

WINDOW_T1 = 83
WINDOW_T2 = 437

RETAINED_RANK_R1 = 9
RETAINED_RANK_R2 = 12

# Transient removal / analysis segment.
ANALYSIS_START_INDEX = 1000
ANALYSIS_END_INDEX = 20000

# Peak detection is used only for Fig. 3(b) histograms.
A1_PEAK_PROMINENCE = 0.12
A1_PEAK_DISTANCE = 5

BETA1_PEAK_PROMINENCE = 0.12
BETA1_PEAK_DISTANCE = 15

# Fig. 3(d) x-axis range in absolute raw simulation time.
FIG3D_TIME_MIN = 20.0
FIG3D_TIME_MAX = 60.0


# ============================================================
# Figure style
# ============================================================

plt.rcParams["font.family"] = "Arial"
plt.rcParams["mathtext.fontset"] = "custom"
plt.rcParams["mathtext.rm"] = "Arial"
plt.rcParams["mathtext.it"] = "Arial:italic"
plt.rcParams["mathtext.bf"] = "Arial:bold"
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["svg.fonttype"] = "none"


def load_raw_data():
    """Load raw KS data generated by 01_generate_ks_raw_data.py."""
    if not os.path.exists(RAW_DATA_FILE):
        raise FileNotFoundError(
            f"{RAW_DATA_FILE} was not found. Run 01_generate_ks_raw_data.py first."
        )
    return np.load(RAW_DATA_FILE)


def reset_output_dir():
    """Delete old outputs and create a clean SVG-only output folder."""
    if os.path.isdir(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR)
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def save_svg(fig, file_stem):
    """Save one figure as SVG only."""
    path = os.path.join(OUTPUT_DIR, f"{file_stem}.svg")
    fig.savefig(path, format="svg", facecolor="white", transparent=False)
    print(f"Saved: {path}")


def paper_axes(ax):
    """Single-axis paper style."""
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.0)
    ax.spines["bottom"].set_linewidth(1.0)
    ax.tick_params(direction="out", length=3.5, width=1.0, pad=3)


def twin_axes_style(ax1, ax2):
    """Twin-axis paper style."""
    ax1.spines["top"].set_visible(False)
    ax2.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)
    ax2.spines["left"].set_visible(False)
    ax1.spines["left"].set_linewidth(1.0)
    ax1.spines["bottom"].set_linewidth(1.0)
    ax2.spines["right"].set_linewidth(1.0)
    ax1.tick_params(direction="out", length=3.5, width=1.0, pad=3)
    ax2.tick_params(direction="out", length=3.5, width=1.0, pad=3)


# ============================================================
# KS equation and modal velocity
# ============================================================

def ks_fourier_rhs(t, a, FOURIER_MODES=FOURIER_MODES, NU=NU):
    """Truncated Fourier-mode KS equation used to evaluate da/dt."""
    _ = t
    a_dot = np.zeros(FOURIER_MODES, dtype=np.float64)

    for k in range(1, FOURIER_MODES + 1):
        nonlinear_term = 0.0

        for m in range(-FOURIER_MODES, FOURIER_MODES + 1):
            if m > 0:
                a_m = a[m - 1]
            elif m < 0:
                a_m = -a[-m - 1]
            else:
                a_m = 0.0

            if 0 < k - m < FOURIER_MODES:
                a_km = a[k - m - 1]
            elif -FOURIER_MODES < k - m < 0:
                a_km = -a[m - k - 1]
            else:
                a_km = 0.0

            nonlinear_term += a_m * a_km

        a_dot[k - 1] = (k ** 2 - NU * k ** 4) * a[k - 1] - k * nonlinear_term

    return a_dot


def compute_modal_velocity(observable_matrix_H, analysis_time_grid_t):
    """Compute da/dt on the selected analysis segment."""
    observable_velocity_matrix_H_dot = np.zeros_like(observable_matrix_H)

    for i in range(observable_matrix_H.shape[1]):
        observable_velocity_matrix_H_dot[:, i] = ks_fourier_rhs(analysis_time_grid_t[i], observable_matrix_H[:, i], FOURIER_MODES, NU)

    return observable_velocity_matrix_H_dot


# ============================================================
# SVD reduction and closure defect
# ============================================================

def compute_reduced_coordinates_V(observable_matrix_H_input, observable_velocity_matrix_H_dot_input, retained_rank_r):
    """
    Apply SVD to the observable matrix and return reduced coordinates.

    H = U Sigma V^T
    reduced_coordinates_V = Sigma_r V_r^T
    dY/dt = left_singular_vectors_U_r^T dH/dt

    Here H is the raw 16-Fourier-mode observable matrix.
    """
    U, singular_values_all, Vh = np.linalg.svd(observable_matrix_H_input, full_matrices=False)

    left_singular_vectors_U_r = U[:, :retained_rank_r]
    singular_values_r = singular_values_all[:retained_rank_r]
    right_singular_vectors_Vh_r = Vh[:retained_rank_r, :]

    reduced_coordinates_V = np.diag(singular_values_r) @ right_singular_vectors_Vh_r
    reduced_velocity_V_dot = left_singular_vectors_U_r.T @ observable_velocity_matrix_H_dot_input

    return reduced_coordinates_V, reduced_velocity_V_dot


def prepare_window_sums_for_A_t_and_R_t(reduced_coordinates_V, reduced_velocity_V_dot):
    """Precompute cumulative matrices for sliding-window least-squares fits."""
    retained_rank_r, _ = reduced_coordinates_V.shape

    V_V_transpose_per_time = np.einsum("ik,jk->kij", reduced_coordinates_V, reduced_coordinates_V)
    V_dot_V_transpose_per_time = np.einsum("ik,jk->kij", reduced_velocity_V_dot, reduced_coordinates_V)

    cumulative_V_V_transpose = np.concatenate([np.zeros((1, retained_rank_r, retained_rank_r)), np.cumsum(V_V_transpose_per_time, axis=0)], axis=0)
    cumulative_V_dot_V_transpose = np.concatenate([np.zeros((1, retained_rank_r, retained_rank_r)), np.cumsum(V_dot_V_transpose_per_time, axis=0)], axis=0)
    cumulative_V_dot_squared_norm = np.concatenate([np.zeros((retained_rank_r, 1)), np.cumsum(reduced_velocity_V_dot ** 2, axis=1)], axis=1)

    return cumulative_V_V_transpose, cumulative_V_dot_V_transpose, cumulative_V_dot_squared_norm


def compute_closure_defect_beta_for_window_T(cumulative_V_V_transpose, cumulative_V_dot_V_transpose, cumulative_V_dot_squared_norm, window_length_T):
    """
    Compute local Koopman closure defect beta(t; T, r).

    Within each sliding window:
        A_t = dV V^dagger
        R = dV - A_t V
        beta = row-averaged ||R||_2
    """
    n_time_columns = cumulative_V_dot_squared_norm.shape[1] - 1

    if window_length_T >= n_time_columns:
        raise ValueError(
            f"window_length_T={window_length_T} is too large for sequence length {n_time_columns}."
        )

    closure_defect_beta_values = np.zeros(n_time_columns - window_length_T)

    for start in range(n_time_columns - window_length_T):
        end = start + window_length_T

        V_t_V_t_transpose = cumulative_V_V_transpose[end] - cumulative_V_V_transpose[start]
        V_dot_t_V_t_transpose = cumulative_V_dot_V_transpose[end] - cumulative_V_dot_V_transpose[start]
        V_dot_t_squared_norm_sum = cumulative_V_dot_squared_norm[:, end] - cumulative_V_dot_squared_norm[:, start]

        A_t = V_dot_t_V_t_transpose @ np.linalg.pinv(V_t_V_t_transpose)

        R_t_row_squared_norms = (
            V_dot_t_squared_norm_sum
            - 2.0 * np.einsum("ij,ij->i", A_t, V_dot_t_V_t_transpose)
            + np.einsum("ij,jk,ik->i", A_t, V_t_V_t_transpose, A_t)
        )

        closure_defect_beta_values[start] = np.mean(np.sqrt(np.maximum(R_t_row_squared_norms, 0.0)))

    return closure_defect_beta_values


# ============================================================
# Fig. 3(b) histogram support
# ============================================================

def first_mode_a1_peak_valley_indices(first_mode_a1):
    """Return peak-valley extrema of first_mode_a1 for the WINDOW_T1 interval histogram."""
    peaks, _ = find_peaks(first_mode_a1, prominence=A1_PEAK_PROMINENCE, distance=A1_PEAK_DISTANCE)
    valleys, _ = find_peaks(-first_mode_a1, prominence=A1_PEAK_PROMINENCE, distance=A1_PEAK_DISTANCE)
    return np.sort(np.concatenate([peaks, valleys]))


def closure_defect_beta1_peak_indices(closure_defect_beta1):
    """Return closure_defect_beta1 peaks for the WINDOW_T2 interval histogram."""
    peaks, _ = find_peaks(closure_defect_beta1, prominence=BETA1_PEAK_PROMINENCE, distance=BETA1_PEAK_DISTANCE)
    return peaks


def interval_distribution(indices):
    """Return interval values and their counts."""
    if indices is None or len(indices) < 2:
        return np.array([], dtype=int), np.array([], dtype=int), np.array([], dtype=int)

    intervals = np.diff(np.asarray(indices)).astype(int)
    values, counts = np.unique(intervals, return_counts=True)
    return intervals, values, counts


# ============================================================
# Figures
# ============================================================

def plot_fig3b(first_mode_a1_extrema, closure_defect_beta1_peaks):
    """Fig. 3(b): two-layer window-selection histograms."""
    _, values1, counts1 = interval_distribution(first_mode_a1_extrema)
    _, values2, counts2 = interval_distribution(closure_defect_beta1_peaks)

    fig = plt.figure(figsize=(10, 3), dpi=300, facecolor="white")
    ax1 = fig.add_axes([0.105, 0.23, 0.320, 0.68], facecolor="white")
    ax2 = fig.add_axes([0.569, 0.23, 0.320, 0.68], facecolor="white")

    label_size = 20
    tick_size = 20

    if values1.size > 0:
        ax1.bar(values1, counts1, width=0.9, edgecolor="black", linewidth=0.6, color="black")
        ax1.axvline(WINDOW_T1, linestyle="--", linewidth=1.1, color="black")
        ax1.set_ylim(0, max(int(counts1.max()), 1) * 1.20)
        ax1.set_ylabel("Count", fontsize=label_size, labelpad=8)
        ax1.tick_params(axis="both", labelsize=tick_size, labelcolor="black")
        ax1.xaxis.set_major_locator(MaxNLocator(nbins=4))
        ax1.yaxis.set_major_locator(MaxNLocator(nbins=3))
    else:
        ax1.text(0.5, 0.5, "Not enough peaks", ha="center", va="center",
                 fontsize=label_size, transform=ax1.transAxes)
        ax1.set_axis_off()

    if values2.size > 0:
        ax2.bar(values2, counts2, width=0.9, edgecolor="black", linewidth=0.6, color="black")
        ax2.axvline(WINDOW_T2, linestyle="--", linewidth=1.1, color="black")
        ax2.set_ylim(0, max(int(counts2.max()), 1) * 1.20)
        ax2.set_ylabel("Count", fontsize=label_size, labelpad=8)
        ax2.tick_params(axis="both", labelsize=tick_size, labelcolor="black")
        ax2.xaxis.set_major_locator(MaxNLocator(nbins=4))
        ax2.yaxis.set_major_locator(MaxNLocator(nbins=3))
    else:
        ax2.text(0.5, 0.5, "Not enough peaks", ha="center", va="center",
                 fontsize=label_size, transform=ax2.transAxes)
        ax2.set_axis_off()

    for ax in [ax1, ax2]:
        paper_axes(ax)
        ax.grid(False)

    fig.text(
        0.5,
        0.08,
        r"Peak interval $\Delta k$ (samples)",
        ha="center",
        va="center",
        fontsize=label_size
    )

    save_svg(fig, "fig3b_window_selection")
    plt.close(fig)


def plot_fig3c(closure_defect_beta2, first_mode_a1, plot_time):
    """Fig. 3(c): long-window closure_defect_beta2 with first_mode_a1."""
    t_beta2 = plot_time[:len(closure_defect_beta2)]

    fig = plt.figure(figsize=(10, 3), dpi=300, facecolor="white")
    ax1 = fig.add_axes([0.105, 0.28, 0.765, 0.58], facecolor="white")
    ax2 = ax1.twinx()

    line_beta, = ax1.plot(
        t_beta2,
        closure_defect_beta2,
        color="#C42238",
        linewidth=1.1,
        alpha=0.80,
        label=r"$\beta_2$"
    )
    line_a1, = ax2.plot(
        plot_time,
        first_mode_a1,
        color="#034A29",
        linewidth=1.0,
        alpha=0.85,
        label=r"$a_1$"
    )

    ax1.set_xlabel(r"$t$", fontsize=20, labelpad=6)
    ax1.set_ylabel(r"$\beta_2$", fontsize=20, labelpad=6)
    ax2.set_ylabel(r"$a_1$", fontsize=20, labelpad=6)

    ax1.tick_params(axis="both", labelsize=20)
    ax2.tick_params(axis="both", labelsize=20)
    ax2.tick_params(axis="x", bottom=False, labelbottom=False)

    ax1.xaxis.set_major_locator(MaxNLocator(nbins=5))
    ax1.yaxis.set_major_locator(MaxNLocator(nbins=4))
    ax2.yaxis.set_major_locator(MaxNLocator(nbins=3))

    ax1.margins(x=0.01, y=0.06)
    ax2.margins(x=0.01, y=0.06)

    twin_axes_style(ax1, ax2)

    ax1.legend(
        [line_beta, line_a1],
        [r"$\beta_2$", r"$a_1$"],
        loc="upper right",
        fontsize=12,
        frameon=False,
        ncol=2
    )

    save_svg(fig, "fig3c_long_window_beta")
    plt.close(fig)


def plot_fig3d(closure_defect_beta1, first_mode_a1, plot_time):
    """Fig. 3(d): short-window closure_defect_beta1 with first_mode_a1 in the raw-time interval."""
    t_beta1 = plot_time[:len(closure_defect_beta1)]

    beta_mask = (t_beta1 >= FIG3D_TIME_MIN) & (t_beta1 <= FIG3D_TIME_MAX)
    a1_mask = (plot_time >= FIG3D_TIME_MIN) & (plot_time <= FIG3D_TIME_MAX)

    fig = plt.figure(figsize=(10, 3), dpi=300, facecolor="white")
    ax1 = fig.add_axes([0.105, 0.30, 0.765, 0.56], facecolor="white")
    ax2 = ax1.twinx()

    line_beta, = ax1.plot(
        t_beta1[beta_mask],
        closure_defect_beta1[beta_mask],
        color="#C42238",
        linewidth=1.1,
        alpha=0.80,
        label=r"$\beta_1$"
    )
    line_a1, = ax2.plot(
        plot_time[a1_mask],
        first_mode_a1[a1_mask],
        color="#034A29",
        linewidth=1.0,
        alpha=0.85,
        label=r"$a_1$"
    )

    ax1.set_xlim(FIG3D_TIME_MIN, FIG3D_TIME_MAX)

    ax1.set_xlabel(r"$t$", fontsize=20, labelpad=6)
    ax1.set_ylabel(r"$\beta_1$", fontsize=20, labelpad=6)
    ax2.set_ylabel(r"$a_1$", fontsize=20, labelpad=6)

    ax1.tick_params(axis="both", labelsize=20)
    ax2.tick_params(axis="both", labelsize=20)
    ax2.tick_params(axis="x", bottom=False, labelbottom=False)

    ax1.xaxis.set_major_locator(MaxNLocator(nbins=5))
    ax1.yaxis.set_major_locator(MaxNLocator(nbins=4))
    ax2.yaxis.set_major_locator(MaxNLocator(nbins=3))

    ax1.margins(x=0.01, y=0.06)
    ax2.margins(x=0.01, y=0.06)

    twin_axes_style(ax1, ax2)

    ax1.legend(
        [line_beta, line_a1],
        [r"$\beta_1$", r"$a_1$"],
        loc="upper right",
        fontsize=12,
        frameon=False,
        ncol=2
    )

    save_svg(fig, "fig3d_short_window_beta")
    plt.close(fig)


# ============================================================
# Main workflow
# ============================================================

def main():
    reset_output_dir()

    raw = load_raw_data()

    t = raw["t"]
    a = raw["a"]

    observable_matrix_H = a[:, ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]
    analysis_time_grid_t = t[ANALYSIS_START_INDEX:ANALYSIS_END_INDEX]

    # Absolute raw simulation time is used for every x-axis.
    plot_time = analysis_time_grid_t

    first_mode_a1 = observable_matrix_H[0, :]

    print("Raw data shape:", a.shape)
    print("Analysis data shape:", observable_matrix_H.shape)
    print(f"Using manuscript parameters: WINDOW_T1={WINDOW_T1}, WINDOW_T2={WINDOW_T2}, RETAINED_RANK_R1={RETAINED_RANK_R1}, RETAINED_RANK_R2={RETAINED_RANK_R2}")
    print(f"Fig. 3(d) raw-time xlim = {FIG3D_TIME_MIN}:{FIG3D_TIME_MAX}")

    print("Computing modal velocities...")
    observable_velocity_matrix_H_dot = compute_modal_velocity(observable_matrix_H, analysis_time_grid_t)

    print("Computing closure_defect_beta1 with manuscript WINDOW_T1 and RETAINED_RANK_R1...")
    reduced_coordinates_V1, reduced_velocity_V1_dot = compute_reduced_coordinates_V(observable_matrix_H, observable_velocity_matrix_H_dot, RETAINED_RANK_R1)
    cumulative_V1_V1_transpose, cumulative_V1_dot_V1_transpose, cumulative_V1_dot_squared_norm = prepare_window_sums_for_A_t_and_R_t(reduced_coordinates_V1, reduced_velocity_V1_dot)
    closure_defect_beta1 = compute_closure_defect_beta_for_window_T(cumulative_V1_V1_transpose, cumulative_V1_dot_V1_transpose, cumulative_V1_dot_squared_norm, WINDOW_T1)

    print("Computing closure_defect_beta2 with manuscript WINDOW_T2 and RETAINED_RANK_R2...")
    reduced_coordinates_V2, reduced_velocity_V2_dot = compute_reduced_coordinates_V(observable_matrix_H, observable_velocity_matrix_H_dot, RETAINED_RANK_R2)
    cumulative_V2_V2_transpose, cumulative_V2_dot_V2_transpose, cumulative_V2_dot_squared_norm = prepare_window_sums_for_A_t_and_R_t(reduced_coordinates_V2, reduced_velocity_V2_dot)
    closure_defect_beta2 = compute_closure_defect_beta_for_window_T(cumulative_V2_V2_transpose, cumulative_V2_dot_V2_transpose, cumulative_V2_dot_squared_norm, WINDOW_T2)

    first_mode_a1_extrema = first_mode_a1_peak_valley_indices(first_mode_a1)
    closure_defect_beta1_peaks = closure_defect_beta1_peak_indices(closure_defect_beta1)

    plot_fig3b(first_mode_a1_extrema, closure_defect_beta1_peaks)
    plot_fig3c(closure_defect_beta2, first_mode_a1, plot_time)
    plot_fig3d(closure_defect_beta1, first_mode_a1, plot_time)

    print("Finished. SVG figures are saved in:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
